CREATE TABLE URL (
    ID INT NOT NULL AUTO_INCREMENT, 
    MINI VARCHAR(6) NOT NULL,
    BASE VARCHAR(255) NOT NULL,
    DATE_CREATED DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX MINIS ON URL (MINI);